title: Deep Dive Podcast
description: Notes and Blogs
baseurl: "" # Root of your site
url: "https://deepdivepod.eu"

theme: minima
plugins:
  - jekyll-feed

collections:
  episodes:
    output: true
    permalink: /episodes/:name/