backend:
  name: github
  repo: ivetkalchev/deepdivepod
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "episodes"
    label: "Episodes"
    folder: "content/episodes"
    create: true
    slug: "Episode {{fields.episode_number}}: {{slug}}"
    fields:
      - { label: "Episode Number", name: "episode_number", widget: "number", min: 1, step: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Spotify Embed Link", name: "spotify", widget: "string", hint: "Paste the Spotify embed iframe or track URL" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Add one or more tags for this episode"
        field: 
            { label: "Tag", name: "tag", widget: "string" }
      - label: "External Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string", hint: "e.g., YouTube, Apple Podcasts" }
          - { label: "URL", name: "url", widget: "string" }