backend:
  name: github
  branch: main
  repo: ivetkalchev/deepdivepod

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "episodes"
    label: "Episodes"
    folder: "_episodes"
    create: true
    slug: "{{fields.episode_number}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "episode" }
      - { label: "Episode Number", name: "episode_number", widget: "number", min: 1, step: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Spotify Embed Link", name: "spotify", widget: "string", hint: "Paste the Spotify embed iframe or track URL" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: 
          { label: "Tag", name: "tag", widget: "string" }
      - label: "External Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string", hint: "e.g., YouTube, Apple Podcasts" }
          - { label: "URL", name: "url", widget: "string" }

    episodes:
      output: true